# Generated by Django 6.0 on 2025-12-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.PositiveIntegerField()),
                ('posicao', models.CharField(max_length=100)),
                ('nascimento', models.CharField(max_length=200)),
                ('foto_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(max_length=200)),
                ('autor_projeto', models.CharField(max_length=100)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('ano_copyright', models.CharField(blank=True, max_length=10)),
                ('descricao_site', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Informação do Site',
                'verbose_name_plural': 'Informações do Site',
            },
        ),
    ]
